baseurl = "/"
languageCode = "zh-cn"
title = "IPFS 佛经"
theme = "apporc"
metadataformat = "yaml"
canonifyURLs = false
relativeURLs = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-113782954-1"

[params]
	# General information
	author = "apporc"
	description = "Sutra on IPFS."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
  ipfs_url = "https://ipfs.io/ipns/QmbcQfKDQ5WQZhAsycw9nxNNJjakLLDSJ2eERDTTirXbSG"
  repo_url = "https://github.com/apporc/sutra_ipfs.git"

	version = "1.0.0"
	logo = "images/logo.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-orange"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "般若波罗蜜多心经"
	url    = "xinjing/"
	weight = 1

[[menu.main]]
	name   = "金刚般若波罗蜜经"
	url    = "jingangjing/"
	weight = 2


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
