baseurl = "http://localhost:1313/"
languageCode = "zh-cn"
title = "Sutra On IPFS"
theme = "apporc"
metadataformat = "yaml"
canonifyurls = false
relativeurls = false
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "apporc"
	description = "sutra on ipfs."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/apporc/sutra_ipfs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-orange"
    	accent  = "orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "Index"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "般若波罗蜜多心经"
	url    = "xinjing"
	weight = 10

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
